v7a: barebox: version bump 2025.05.0 -> 2025.06.0
Barebox commit 9c3afd5083a3 (included in v2025.06.0) fixes an error
message with the OMAP RNG on Beaglebone:

  ERROR: omap_rng 48310000.rng@0.of: initialization failed.
  ERROR: omap_rng 48310000.rng@0.of: initialization failed.
  ERROR: omap_rng 48310000.rng@0.of: probe failed: Device or resource busy

Bump the version number, run oldconfig with defaults, and update the
remaining platform-specific bareboxes as well.

Link: https://git.pengutronix.de/cgit/barebox/commit/?id=9c3afd5083a3
Signed-off-by: Roland Hieber <rhi@pengutronix.de>