v8a: tf-a: make it compile with GCC 15
Due to -Wall, GCC 15 complains about the header guard:

    CC      plat/imx/imx93/trdc.c
  In file included from drivers/nxp/trdc/imx_trdc.c:13:
  include/drivers/nxp/trdc/imx_trdc.h:7: error: header guard 'IMX_TRDC_H' followed by '#define' of a different macro [-Werror=header-guard]
  include/drivers/nxp/trdc/imx_trdc.h:8: note: 'IMX_XRDC_H' is defined here; did you mean 'IMX_TRDC_H'?
  cc1: all warnings being treated as errors

Cherry-pick a patch from upstream to fix this.

Signed-off-by: Roland Hieber <rhi@pengutronix.de>