platform: v8a: platformconfig: Remove duplicate dts file
List contained 'freescale/imx8mn-ddr4-evk.dts' twice, which lead to
stage kernel-fit.targetinstall failing after enabling
PTXCONF_KERNEL_FIT (output truncated):

    --------------------------------
    target: kernel-fit.targetinstall
    --------------------------------

    /tmp/ptxdist.GyYcfh/fitimage.2AzdHm2H:47.27-55.5: ERROR (duplicate_node_names): /images/fdt-fsl,imx8mn-ddr4-evk: Duplicate node name
    /tmp/ptxdist.GyYcfh/fitimage.2AzdHm2H:127.28-131.5: ERROR (duplicate_node_names): /configurations/conf-fsl,imx8mn-ddr4-evk: Duplicate node name
    ERROR: Input tree has errors, aborting (use -f to force output)
    mkimage: Can't open /home/adahl/Work/bsp/thorsis/generic/platform-v8a/images/linuximage.fit.tmp: No such file or directory
    Error: Bad parameters for FIT image type
    Usage: mkimage [-T type] -l image
              -l ==> list image header information

Fixes: commit:ed9d5ee0f532 ("v8a: imx8m: include i.MX8MN DDR4 and LPDDR4 EVK DT in rootfs")
Signed-off-by: Alexander Dahl <ada@thorsis.com>
Reviewed-by: Ahmad Fatoum <a.fatoum@pengutronix.de>