v7a: barebox: enable HWRNG drivers and allow fallback to PRNG
Without an HWRNG available, barebox prints an unsightly error message
on boot:

    ERROR: no HWRNG available!

Since we don't have HWRNG drivers for all available platforms, enable
those that we have (RPi, AM33xx, and FSL CAAM for i.MX6), and for the
other platforms allow fallback to the PRNG, which will at least only
print a warning on boot on platforms without HWRNG:

    WARNING: falling back to Pseudo RNG source!

… but in this case, this is expected.

Signed-off-by: Roland Hieber <rhi@pengutronix.de>